# Generated by Django 5.0.4 on 2024-04-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('cuerpo', models.TextField()),
                ('adulto', models.BooleanField()),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
