# Generated by Django 5.0.6 on 2024-05-17 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('direccion', models.TextField(max_length=150)),
                ('contacto', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('especialidad', models.TextField(max_length=150)),
                ('contacto', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(max_length=150)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.edificio')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tecnico')),
            ],
        ),
    ]
