# Generated by Django 5.0.4 on 2024-05-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Clásica', 'Música Clásica'), ('Electrónica', 'Electrónica'), ('Hip Hop', 'Hip Hop'), ('Reggae', 'Reggae'), ('Metal', 'Metal'), ('Blues', 'Blues'), ('Country', 'Country')], max_length=20),
        ),
    ]
